config/routes.rb
Rails.application.routes.draw do
  root 'to_do_lists#index'
  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'
  get '/account', to: 'users#edit'
  patch '/account', to: 'users#update'
  delete '/account', to: 'users#destroy'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  resources :to_do_lists, only: [:index, :new, :create, :show, :update, :destroy] do
    resources :to_do_list_items, only: [:create, :update, :destroy], shallow: true
  end
  patch 'to_do_list_items/:id/done', to: 'to_do_list_items#done', as: :to_do_list_item_done

  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      post '/token', to: 'sessions#create'
      delete '/token', to: 'sessions#destroy'
      resources :users, only: [:show, :update, :destroy]
      resources :to_do_lists, only: [:index, :show, :create, :update, :destroy] do
        resources :to_do_list_items, only: [:index, :show, :create, :update, :destroy]
      end
    end
  end

end

app/models/to_do_list_item.rb
class ToDoListItem < ApplicationRecord
  belongs_to :to_do_list
  validates :content, presence: true
  validates :to_do_list, presence: true
end

app/controllers/api/v1/to_do_list_items_controller.rb
class Api::V1::ToDoListItemsController < Api::V1::BaseController

  before_action :authenticate_with_token!, only: [:index, :show, :create, :update, :destroy]
  before_action :list_belongs_to_user, only: [:index, :show, :create, :update, :destroy]

  def index
    render json: to_do_list.to_do_list_items
  end

  def show
    @to_do_list_item = to_do_list.to_do_list_items.find_by(id: params[:id])
    if @to_do_list_item
      render json: @to_do_list_item
    else
      head 404
    end
  end

  def create
    @to_do_list_item = to_do_list.to_do_list_items.new(to_do_list_item_params)
    if @to_do_list_item.save
      render json: @to_do_list_item, status: 201
    else
      render json: { errors: @to_do_list_item.errors }, status: 422
    end
  end

  def update
    @to_do_list_item = to_do_list.to_do_list_items.find_by(id: params[:id])
    if @to_do_list_item
      if @to_do_list_item.update(to_do_list_item_params)
        render json: @to_do_list_item
      else
        render json: { errors: @to_do_list_item.errors }, status: 422
      end
    else
      head 404
    end
  end

  def destroy
    @to_do_list_item = to_do_list.to_do_list_items.find_by(id: params[:id])
    if @to_do_list_item
      @to_do_list_item.destroy
      head 204
    else
      head 404
    end
  end

  private

  def to_do_list
    @to_do_list ||= ToDoList.find_by(id: params[:to_do_list_id])
  end

  def list_belongs_to_user
    unless current_user.to_do_lists.include?(to_do_list)
      head 404
    end
  end

  def to_do_list_item_params
    params.require(:to_do_list_item).permit(:content, :done)
  end

end

app/controllers/to_do_list_items_controller.rb
class ToDoListItemsController < ApplicationController

  before_action :list_belongs_to_user, only: [:create]
  before_action :item_belongs_to_user, only: [:update, :destroy, :done]

  def create
    @to_do_list_item = ToDoListItem.new(to_do_list_item_params.merge(to_do_list_id: params[:to_do_list_id]))
    respond_to do |format|
      if @to_do_list_item.save
        format.js
      else
        format.json {render json: @to_do_list_item.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    @to_do_list_item = ToDoListItem.find(params[:id])
    @to_do_list_item.update(to_do_list_item_params)
    respond_with_bip(@to_do_list_item)
  end

  def done
    respond_to do |format|
      @to_do_list_item = ToDoListItem.find(params[:id])
      @to_do_list_item.update(to_do_list_item_done_params)
      format.js
    end
  end

  def destroy
    respond_to do |format|
      @to_do_list_item = ToDoListItem.find(params[:id])
      format.js
    end
  end

  private
    def to_do_list_item_params
      params.require(:to_do_list_item).permit(:content)
    end

    def to_do_list_item_done_params
      params.require(:to_do_list_item).permit(:done)
    end

    def to_do_list
      @to_do_list ||= ToDoList.find(params[:to_do_list_id])
    end

    def to_do_list_item
      @to_do_list_item ||= ToDoListItem.find(params[:id])
    end

    def item_belongs_to_user
      unless logged_in? && current_user.to_do_lists.include?(to_do_list_item.to_do_list)
        not_found
      end
    end
end

app/views/to_do_list_items/_to_do_list_item.html.erb
<tr id="to_do_list_item<%= to_do_list_item.id %>" class="<%= 'done' if to_do_list_item.done? %>">
  <td>
      <%= form_with model: to_do_list_item, url: to_do_list_item_done_url(to_do_list_item) do |f| %>
        <%= f.check_box :done %>
        <%= f.submit 'Send', style: 'display: none'  %>
      <% end %>
  </td>
  <td>
    <%= best_in_place to_do_list_item, :content, url: '#', inner_class: 'form-control' %>
  </td>
  <td><%= link_to I18n.t('to_do_list_item.delete'), to_do_list_item_url(to_do_list_item), method: :delete, class: 'btn btn-danger btn-sm float-right', remote: true %></td>
</tr>

app/views/to_do_list_items/create.js.erb
to_do_list = $("<%= escape_javascript(render @to_do_list_item) %>");
to_do_list2 = $("<%= escape_javascript(render @to_do_list_item) %>");
to_do_list.hide();
$('table.to_do_list_items').append(to_do_list);
$('table.to_do_list_items').append(to_do_list2);
$('input[name="to_do_list_item[content]"]').val('');
to_do_list.show('slow');
jQuery('.best_in_place').best_in_place();
$("input[name='to_do_list_item[done]']").on("click", function() {
  $(this).parents("form:first").find("input[type='submit']").click()
})

app/views/to_do_list_items/destroy.js.erb
$("#to_do_list_item<%= @to_do_list_item.id %>").hide('slow', function(){ this.remove(); });

app/views/to_do_list_items/done.js.erb
<% if @to_do_list_item.done? %>
$("#to_do_list_item<%= @to_do_list_item.id %>").addClass("done")
<% else %>
$("#to_do_list_item<%= @to_do_list_item.id %>").removeClass("done")
<% end %>