config/routes.rb
Rails.application.routes.draw do
  root 'to_do_lists#index'
  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'
  get '/account', to: 'users#edit'
  patch '/account', to: 'users#update'
  delete '/account', to: 'users#destroy'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  resources :to_do_lists, only: [:index, :new, :create, :show, :update, :destroy] do
    resources :to_do_list_items, only: [:create, :update, :destroy], shallow: true
  end
  patch 'to_do_list_items/:id/done', to: 'to_do_list_items#done', as: :to_do_list_item_done

  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      post '/token', to: 'sessions#create'
      delete '/token', to: 'sessions#destroy'
      resources :users, only: [:show, :update, :destroy]
      resources :to_do_lists, only: [:index, :show, :create, :update, :destroy] do
        resources :to_do_list_items, only: [:index, :show, :create, :update, :destroy]
      end
    end
  end

end

app/models/to_do_list.rb
class ToDoList < ApplicationRecord
  belongs_to :user
  # validates :title, presence: true
  validates :user, presence: true
  has_many :to_do_list_items, dependent: :destroy
end

app/controllers/api/v1/to_do_lists_controller.rb
class Api::V1::ToDoListsController < Api::V1::BaseController

  before_action :authenticate_with_token!, only: [:index, :show, :create, :update, :destroy]

  def index
    @user = current_user
    render json: @user.to_do_lists, except: [:user_id], status: 200
  end

  def show
    @user = current_user
    @to_do_list = @user.to_do_lists.find_by(id: params[:id])
    if @to_do_list
      render json: @to_do_list, except: [:user_id], status: 200
    else
      head 404
    end
  end

  def create
    @user = current_user
    @to_do_list = @user.to_do_lists.new(to_do_list_params)
    if @to_do_list.save
      render json: @to_do_list, except: [:user_id], status: 201
    else
      render json: { errors: @to_do_list.errors }, status: 422
    end
  end

  def update
    @user = current_user
    @to_do_list = @user.to_do_lists.find_by(id: params[:id])
    if @to_do_list
      if @to_do_list.update(to_do_list_params)
        render json: @to_do_list, except: [:user_id], status: 200
      else
        render json: { errors: @to_do_list.errors }, status: 422
      end
    else
      head 404
    end
  end

  def destroy
    @user = current_user
    @to_do_list = @user.to_do_lists.find_by(id: params[:id])
    if @to_do_list
      @to_do_list.destroy
      head 204
    else
      head 404
    end
  end

  private

  def to_do_list_params
    params.require(:to_do_list).permit(:title)
  end

end

app/controllers/to_do_lists_controller.rb
class ToDoListsController < ApplicationController

  before_action :list_belongs_to_user, only: [:update, :destroy]
  before_action :logged_in_user, only: [:new, :create]

  def index
    @user = current_user
  end

  def show
    session[:last_list_id] = to_do_list.id
  end

  def new
    @to_do_list = ToDoList.new
  end

  def create
    @to_do_list = current_user.to_do_lists.new(to_do_list_params)
    if @to_do_list.save
      flash[:success] = I18n.t('to_do_list.flashes.list_created')
      redirect_to to_do_list_path(@to_do_list)
    else
      render 'new'
    end
  end

  def update
    @to_do_list = ToDoList.find(params[:id])
    @to_do_list.update(to_do_list_params)
    respond_with_bip(@to_do_list)
  end

  def destroy
    @to_do_list = ToDoList.find(params[:id])
    @to_do_list.destroy
    flash[:danger] = I18n.t('to_do_list.flashes.list_deleted')
    redirect_to to_do_lists_path
  end

  private

    def to_do_list_params
      params.require(:to_do_list).permit(:title)
    end

    def to_do_list
      @to_do_list ||= ToDoList.find(params[:id])
    end
end

app/views/to_do_lists/_to_do_list.html.erb
<div class="col-sm-4">
  <%= link_to to_do_list do %>
    <div class="card">
      <h4><%= to_do_list.title %></h4>
      <p><%= pluralize(to_do_list.to_do_list_items.count + 1, 'item') %></p>
    </div>
  <% end %>
</div>

app/views/to_do_lists/index.html.erb
<% if @user %>
  <% if @user.to_do_lists.any? %>
    <div class="row">
      <% @user.to_do_lists.each do |to_do_list| %>
        <%= render to_do_list %>
      <% end %>
    </div>
  <% else %>
    <h3><%= I18n.t('to_do_list.no_lists') %></h3>
  <% end %>
  <%= link_to I18n.t('to_do_list.add'), new_to_do_list_path, class: 'btn btn-primary btn-lg' %>
<% else %>
  <h3><%= I18n.t('to_do_list.login') %></h3>
<% end %>

app/views/to_do_lists/new.html.erb
<div class="row">
  <div class=col-sm-6>
    <%= form_for @to_do_list, url: to_do_lists_path do |f| %>
      <%= render 'shared/error_messages', object: f.object %>
      <div class="form-group">
        <%= f.label :title %>
        <%= f.text_field :title, class: "form-control" %>
      </div>
      <%= f.submit I18n.t('to_do_list.create'), class: "btn btn-primary btn-lg" %>
    <% end %>
  </div>
</div>

app/views/to_do_lists/show.html.erb
<div class="row">
  <div class="col-sm-12">
    <%= best_in_place @to_do_list, :title, class: 'h3', inner_class: 'form-control' %>
    <table class="table table-hover to_do_list_items">
      <% if @to_do_list.to_do_list_items.any? %>
        <%= render @to_do_list.to_do_list_items %>
      <% end %>
    </table>
    <%= form_with(model: ToDoListItem.new, url: to_do_list_to_do_list_items_url(@to_do_list)) do |f| %>
      <%= f.text_field :content, required: true, class: 'form-control' %>
      <%= f.submit I18n.t('to_do_list_item.add_btn'), class: 'btn btn-primary btn-block', data: { disable_with: I18n.t('to_do_list_item.ading') } %>
    <% end %>
    <%= link_to I18n.t('to_do_list.delete_btn'), '#', class: 'btn btn-danger btn-block' %>
  </div>
</div>