config/routes.rb
Rails.application.routes.draw do
  root 'to_do_lists#index'
  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'
  get '/account', to: 'users#edit'
  patch '/account', to: 'users#update'
  delete '/account', to: 'users#destroy'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  resources :to_do_lists, only: [:index, :new, :create, :show, :update, :destroy] do
    resources :to_do_list_items, only: [:create, :update, :destroy], shallow: true
  end
  patch 'to_do_list_items/:id/done', to: 'to_do_list_items#done', as: :to_do_list_item_done

  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      post '/token', to: 'sessions#create'
      delete '/token', to: 'sessions#destroy'
      resources :users, only: [:show, :update, :destroy]
      resources :to_do_lists, only: [:index, :show, :create, :update, :destroy] do
        resources :to_do_list_items, only: [:index, :show, :create, :update, :destroy]
      end
    end
  end

end

app/views/layouts/_flash.html.erb
<% flash.each do |message_type, message| %>
  <%= content_tag(:div, message, class: ['alert', "alert-#{message_type}" ]) %>
<% end %>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-sm bg-light">
  <ul class="navbar-nav mr-auto">
    <% if logged_in? %>
      <li class="nav-item">
        <%= link_to I18n.t('nav_links.my_lists'), root_path, class: 'nav-link' %>
      </li>
      <% unless last_list.nil?  %>
        <li class="nav-item">
          <%= link_to I18n.t('nav_links.last_list'), to_do_list_path(last_list), class: 'nav-link' %>
        </li>
      <% end %>
    <% else %>
      <li class="nav-item">
        <%= link_to I18n.t('nav_links.sign_up'), signup_path, class: 'nav-link' %>
      </li>
    <% end %>
  </ul>
  <ul class="navbar-nav float-right">
    <% if logged_in? %>
      <li class="nav-item">
        <%= link_to I18n.t('nav_links.my_account'), account_path, class: 'nav-link' %>
      </li>
      <li class="nav-item">
        <%= link_to I18n.t('nav_links.log_out'), logout_path, method: :delete, class: 'nav-link' %>
      </li>
    <% else %>
      <li class="nav-item">
        <%= link_to I18n.t('nav_links.log_in'), login_path, class: 'nav-link' %>
      </li>
    <% end %>
  </ul>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ToDo Lists App</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload'%>
  </head>

  <body>
    <div class="container">
      <h1 class="text-center">ToDo Lists App</h1>
      <hr>
      <%= render 'layouts/navigation' %>
      <hr>
    </div>
    <div class="container">
      <%= render 'layouts/flash' %>
      <%= yield %>
    </div>
    <footer>
      <div class="container">
        <p class=text-center>-- ToDo Lists App --</p>
      </div>
    </footer>
  </body>
</html>